-- Generated by SIDIKLAT importer on 2025-10-02 18:05:36 UTC
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;

-- Data pelatihan untuk Madda Elliyana , S.Psi.,M.Psi. (198403092010012007)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Madda Elliyana , S.Psi.,M.Psi.', '198403092010012007', 'Kepala Sub Bagian Umum Dan Kepegawaian', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '198403092010012007'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '198403092010012007'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Peningkatan Kapasitas: Manajemen Implementasi Service Excellence ASN dalam Mengelola Pelayanan Publik yang Profesional',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    24,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Peningkatan Kapasitas: Manajemen Implementasi Service Excellence ASN dalam Mengelola Pelayanan Publik yang Profesional'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Tia Melyana Rotua Simanjuntak , SKM (198202282006042012)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Tia Melyana Rotua Simanjuntak , SKM', '198202282006042012', 'PPUPD Pengawas Pemerintah Madya', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '198202282006042012'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '198202282006042012'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Reviu atas RPJMD dan Renstra',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    60,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Reviu atas RPJMD dan Renstra'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Iwan Setiawan , S.AP (197712241998031004)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Iwan Setiawan , S.AP', '197712241998031004', 'Auditor Kepegawaian Muda', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '197712241998031004'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '197712241998031004'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Agen Perubahan Melalui Sertifikasi Penyuluh Anti Korupsi',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    24,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Agen Perubahan Melalui Sertifikasi Penyuluh Anti Korupsi'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Amaliah Fitri , ST (198406022009032009)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Amaliah Fitri , ST', '198406022009032009', 'Auditor Muda', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '198406022009032009'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '198406022009032009'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Reviu Rencana Kerja dan Anggaran Pemerintah Daerah di lingkungan APIP',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    50,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Reviu Rencana Kerja dan Anggaran Pemerintah Daerah di lingkungan APIP'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Anton Septiadi , SE (198009182010011011)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Anton Septiadi , SE', '198009182010011011', 'Auditor Muda', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '198009182010011011'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '198009182010011011'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Pelatihan Pemeriksaan Barang Milik Daerah Batch 2',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    50,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Pelatihan Pemeriksaan Barang Milik Daerah Batch 2'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Isnaini Inten Prawesti , A.Md (198412032010012007)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Isnaini Inten Prawesti , A.Md', '198412032010012007', 'Auditor Pelaksana Lanjutan', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '198412032010012007'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '198412032010012007'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Reviu Rencana Kerja dan Anggaran Pemerintah Daerah di lingkungan APIP',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    50,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Reviu Rencana Kerja dan Anggaran Pemerintah Daerah di lingkungan APIP'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
-- Data pelatihan untuk Dewi Febriliyanti , S.Ap (199202052022032006)
SET @pegawai_id := NULL;
SET @jenis_pelatihan_id := NULL;
INSERT INTO pegawais
    (nama_lengkap, nip, jabatan, unit_kerja, status, keterangan, jp_target, jp_tercapai, created_at, updated_at)
SELECT
    'Dewi Febriliyanti , S.Ap', '199202052022032006', 'PPUPD Pengawas Pemerintah Pertama', NULL, 'aktif', NULL, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM pegawais WHERE nip = '199202052022032006'
);
SET @pegawai_id := (
    SELECT id FROM pegawais
     WHERE nip = '199202052022032006'
     ORDER BY id DESC
     LIMIT 1
);
INSERT INTO jenis_pelatihans (nama, created_at, updated_at)
SELECT 'Diklat 2025', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM jenis_pelatihans WHERE nama = 'Diklat 2025'
);
SET @jenis_pelatihan_id := (
    SELECT id FROM jenis_pelatihans
     WHERE nama = 'Diklat 2025'
     LIMIT 1
);
INSERT INTO pelatihans
    (pegawai_id, nama_pelatihan, jenis_pelatihan_id, penyelenggara, tempat, tanggal_mulai, tanggal_selesai, jp, status, sertifikat_path, deskripsi, created_at, updated_at)
SELECT
    @pegawai_id,
    'Reviu atas RPJMD dan Renstra',
    @jenis_pelatihan_id,
    NULL,
    NULL,
    NULL,
    NULL,
    60,
    'selesai',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM DUAL
WHERE @pegawai_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM pelatihans
       WHERE pegawai_id = @pegawai_id
      AND nama_pelatihan = 'Reviu atas RPJMD dan Renstra'
      AND (tanggal_mulai IS NULL)
      AND (tanggal_selesai IS NULL)
  );
UPDATE pegawais
   SET jp_tercapai = (
           SELECT COALESCE(SUM(jp), 0)
             FROM pelatihans
            WHERE pelatihans.pegawai_id = pegawais.id
              AND status = 'selesai'
       ),
       updated_at = CURRENT_TIMESTAMP
 WHERE id = @pegawai_id
   AND @pegawai_id IS NOT NULL;
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
